language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  - composer lint
  - composer cs
  - composer phpstan
#  - composer test

services:
  - mysql

addons:
  hosts:
    - mariadb
