FROM vonbraunlabs/php:7.2-apache-composer-redis-extended
WORKDIR /opt
COPY composer.json /opt/
RUN set -ex \
    && mkdir -p /usr/share/man/man1/ /usr/share/man/man3/ /usr/share/man/man7/ \
    && apt-get update \
    && apt-get install -y iputils-ping mysql-client libpq-dev postgresql-client postgresql-client-common telnet \
    && printf "\n" | pecl install mongodb apcu \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql \
    && docker-php-ext-enable mongodb apcu \
    && composer -o install \
    && echo "apc.enable_cli=1" >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
